//! Adversarial empirical test suite for CHG-011 (citations, `[Rn]`) in `crates/document`.
//!
//! Generated by Challenger 1 to stress-test citation and reference entry parsing and resolution.
#![allow(clippy::expect_used, clippy::unwrap_used, clippy::pedantic)]

use document::{Diagnostic, Node, parse};
use library::{RelPath, Source};

fn parse_doc(md: &str) -> document::Document {
    let src = Source::new(RelPath::new("test.md").unwrap(), md.to_string());
    parse(&src)
}

#[test]
fn test_glued_and_boundary_citations() {
    let md = "Text with a[R1]b and [R1][R2] and [R1]-[R2]-[R3] and ([R1]) and \"[R1]\" and [R1].\n\n[R1] Reference one\n\n[R2] Reference two\n\n[R3] Reference three";
    let doc = parse_doc(md);
    assert_eq!(doc.reference_entries.len(), 3);
    assert_eq!(doc.reference_entries[0].label, "R1");
    assert_eq!(doc.reference_entries[0].anchor, "ref-r1");
    assert_eq!(doc.reference_entries[1].label, "R2");
    assert_eq!(doc.reference_entries[1].anchor, "ref-r2");
    assert_eq!(doc.reference_entries[2].label, "R3");
    assert_eq!(doc.reference_entries[2].anchor, "ref-r3");

    // All 9 citations should resolve
    assert_eq!(doc.citations.len(), 9);
    for cit in &doc.citations {
        assert!(cit.target.is_some(), "Citation {:?} should resolve", cit);
    }
    assert!(
        doc.diagnostics.is_empty(),
        "No diagnostics expected: {:?}",
        doc.diagnostics
    );
}

#[test]
fn test_invalid_citation_labels() {
    let md = "[R] [r1] [R1A] [R1ab] [R1_2] [R-1] [R 1] [R1 ] [ R1] [R1\n2]\n\n[R1] Valid entry";
    let doc = parse_doc(md);
    assert_eq!(doc.reference_entries.len(), 1);
    // None of the invalid patterns should be recognized as citations
    assert_eq!(
        doc.citations.len(),
        0,
        "Found citations: {:?}",
        doc.citations
    );
    assert_eq!(
        doc.diagnostics.len(),
        0,
        "Found diagnostics: {:?}",
        doc.diagnostics
    );
}

#[test]
fn test_zero_entries_unresolved_citations_no_diagnostics() {
    let md = "Here is [R1] and [R2] and [R3]. No reference entries on this page.";
    let doc = parse_doc(md);
    assert_eq!(doc.reference_entries.len(), 0);
    assert_eq!(doc.citations.len(), 3);
    assert_eq!(doc.citations[0].target, None);
    assert_eq!(doc.citations[1].target, None);
    assert_eq!(doc.citations[2].target, None);
    assert_eq!(
        doc.diagnostics.len(),
        0,
        "0 diagnostics when 0 reference entries: {:?}",
        doc.diagnostics
    );
}

#[test]
fn test_with_entries_unresolved_citation_emits_diagnostic() {
    let md = "Here is [R1] and [R2].\n\n[R1] Reference one";
    let doc = parse_doc(md);
    assert_eq!(doc.reference_entries.len(), 1);
    assert_eq!(doc.citations.len(), 2);
    assert_eq!(doc.citations[0].target, Some("ref-r1".to_string()));
    assert_eq!(doc.citations[1].target, None);
    assert_eq!(doc.diagnostics.len(), 1);
    match &doc.diagnostics[0] {
        Diagnostic::UnresolvedCitation { label, line } => {
            assert_eq!(label, "R2");
            assert_eq!(*line, 1);
        }
        other => panic!("Unexpected diagnostic: {:?}", other),
    }
}

#[test]
fn test_first_entry_wins_and_duplicate_demotion() {
    let md = "[R1] First definition\n\n[R1] Duplicate definition\n\n[R1] Triplicate definition";
    let doc = parse_doc(md);
    assert_eq!(doc.reference_entries.len(), 1);
    assert_eq!(doc.reference_entries[0].label, "R1");
    assert_eq!(doc.reference_entries[0].line, 1);

    // Duplicates become citations resolving to ref-r1
    assert_eq!(doc.citations.len(), 2);
    assert_eq!(doc.citations[0].label, "R1");
    assert_eq!(doc.citations[0].target, Some("ref-r1".to_string()));
    assert_eq!(doc.citations[0].line, 3);
    assert_eq!(doc.citations[1].label, "R1");
    assert_eq!(doc.citations[1].target, Some("ref-r1".to_string()));
    assert_eq!(doc.citations[1].line, 5);

    // Diagnostics
    assert_eq!(doc.diagnostics.len(), 2);
    match &doc.diagnostics[0] {
        Diagnostic::DuplicateReferenceEntry {
            label,
            first_line,
            second_line,
        } => {
            assert_eq!(label, "R1");
            assert_eq!(*first_line, 1);
            assert_eq!(*second_line, 3);
        }
        other => panic!("Unexpected diagnostic: {:?}", other),
    }
    match &doc.diagnostics[1] {
        Diagnostic::DuplicateReferenceEntry {
            label,
            first_line,
            second_line,
        } => {
            assert_eq!(label, "R1");
            assert_eq!(*first_line, 1);
            assert_eq!(*second_line, 5);
        }
        other => panic!("Unexpected diagnostic: {:?}", other),
    }
}

#[test]
fn test_table_cell_never_reference_entry() {
    let md = "| Header |\n| --- |\n| [R1] in table cell |\n\n[R1] Real reference entry";
    let doc = parse_doc(md);
    // [R1] in table cell must NOT be a reference entry, only [R1] Real reference entry is.
    assert_eq!(doc.reference_entries.len(), 1);
    assert_eq!(doc.reference_entries[0].line, 5);
    assert_eq!(doc.citations.len(), 1);
    assert_eq!(doc.citations[0].target, Some("ref-r1".to_string()));
    assert_eq!(doc.citations[0].line, 3);
    assert!(doc.diagnostics.is_empty());
}

#[test]
fn test_nested_containers() {
    let md = r#"
> [R1] In blockquote
>
> > [R2] In nested blockquote

- [R3] In list item
- Item with sublist:
  - [R4] In nested list item
  - > [R5] In blockquote inside list item

1. [R6] In ordered list
"#;
    let doc = parse_doc(md);
    let labels: Vec<&str> = doc
        .reference_entries
        .iter()
        .map(|e| e.label.as_str())
        .collect();
    assert!(labels.contains(&"R1"), "R1 should be entry");
    assert!(labels.contains(&"R2"), "R2 should be entry");
    assert!(labels.contains(&"R3"), "R3 should be entry");
    assert!(labels.contains(&"R4"), "R4 should be entry");
    assert!(labels.contains(&"R5"), "R5 should be entry");
    assert!(labels.contains(&"R6"), "R6 should be entry");
}

#[test]
fn test_reference_entry_boundary_conditions() {
    let cases = [
        ("[R1] Author", true),
        ("[R1]\nAuthor", true),
        ("[R1] \nAuthor", true),
        ("[R1]  \nAuthor", true),
        ("[R1]   \nAuthor", true),
        ("[R1]", true),
        ("[R1]   ", true),
        ("[R1]\tAuthor", false),
        ("[R1]Author", false),
        ("[R1][R2]", false),
        ("[R1]-[R2]", false),
        ("[R1]. Author", false),
        ("[R1]: Author", false),
    ];

    for (case, should_be_entry) in cases {
        let doc = parse(&Source::new(
            RelPath::new("t.md").unwrap(),
            case.to_string(),
        ));
        let is_entry = doc.reference_entries.iter().any(|e| e.label == "R1");
        assert_eq!(
            is_entry, should_be_entry,
            "Case {:?}: expected is_entry={}, got {}",
            case, should_be_entry, is_entry
        );
    }
}

#[test]
fn test_link_reference_definition_precedence() {
    let md = "[R1]: https://example.com\n\nSee [R1].\n\n[R1] Reference entry";
    let doc = parse(&Source::new(RelPath::new("t.md").unwrap(), md.to_string()));

    // Link reference suppresses citation
    assert_eq!(doc.reference_entries.len(), 0);
    assert_eq!(doc.citations.len(), 0);
    assert_eq!(doc.diagnostics.len(), 0);
    match &doc.body[0] {
        Node::Paragraph(children) => {
            assert!(
                matches!(&children[1], Node::Link { href, .. } if href == "https://example.com")
            );
        }
        other => panic!("Unexpected body: {:?}", other),
    }
}

#[test]
fn test_letter_suffix_entries_and_citations() {
    let md = "See [R12a] and [R12b].\n\n[R12a] Entry A.\n\n[R12b] Entry B.";
    let doc = parse_doc(md);

    assert_eq!(doc.reference_entries.len(), 2);
    assert_eq!(doc.reference_entries[0].label, "R12a");
    assert_eq!(doc.reference_entries[0].anchor, "ref-r12a");
    assert_eq!(doc.reference_entries[1].label, "R12b");
    assert_eq!(doc.reference_entries[1].anchor, "ref-r12b");

    assert_eq!(doc.citations.len(), 2);
    assert_eq!(doc.citations[0].label, "R12a");
    assert_eq!(doc.citations[0].target, Some("ref-r12a".to_string()));
    assert_eq!(doc.citations[1].label, "R12b");
    assert_eq!(doc.citations[1].target, Some("ref-r12b".to_string()));
    assert!(doc.diagnostics.is_empty());
}

#[test]
fn test_context_exclusions() {
    let md = "\
# Heading with [R1]

[R1] Reference Definition.

Inline code `[R1]` must not link.

```
[R1] inside code block
```

Link [R1](https://example.com) must not cite.

Wikilink [[R1]] must not cite.
";
    let doc = parse_doc(md);

    // Exactly one entry: [R1] Reference Definition
    assert_eq!(doc.reference_entries.len(), 1);
    assert_eq!(doc.reference_entries[0].label, "R1");

    // Zero citations recognized because all other [R1] occurrences are in excluded contexts!
    assert_eq!(
        doc.citations.len(),
        0,
        "Expected 0 citations in excluded contexts, got: {:?}",
        doc.citations
    );
    assert!(doc.diagnostics.is_empty());
}

#[test]
fn test_crlf_line_numbers() {
    let md = "[R1] First\r\n\r\n[R2] Second\r\n\r\n[R1] Duplicate\r\n\r\nSee [R3]";
    let doc = parse_doc(md);

    assert_eq!(doc.reference_entries.len(), 2);
    assert_eq!(doc.reference_entries[0].label, "R1");
    assert_eq!(doc.reference_entries[0].line, 1);
    assert_eq!(doc.reference_entries[1].label, "R2");
    assert_eq!(doc.reference_entries[1].line, 3);

    // Duplicate on line 5
    assert_eq!(doc.diagnostics.len(), 2);
    match &doc.diagnostics[0] {
        Diagnostic::DuplicateReferenceEntry {
            label,
            first_line,
            second_line,
        } => {
            assert_eq!(label, "R1");
            assert_eq!(*first_line, 1);
            assert_eq!(*second_line, 5);
        }
        other => panic!("Unexpected diagnostic 0: {:?}", other),
    }

    // Unresolved citation on line 7
    match &doc.diagnostics[1] {
        Diagnostic::UnresolvedCitation { label, line } => {
            assert_eq!(label, "R3");
            assert_eq!(*line, 7);
        }
        other => panic!("Unexpected diagnostic 1: {:?}", other),
    }
}

#[test]
fn test_section_refs_coexistence() {
    let md = "\
# 1. First Section

See §1 and citation [R1].

[R1] Entry One.
";
    let doc = parse_doc(md);

    assert_eq!(doc.headings.len(), 1);
    assert_eq!(doc.reference_entries.len(), 1);
    assert_eq!(doc.citations.len(), 1);
    assert_eq!(doc.section_refs.len(), 1);

    assert_eq!(doc.citations[0].label, "R1");
    assert_eq!(doc.citations[0].target, Some("ref-r1".to_string()));
    assert_eq!(doc.section_refs[0].number, "1");
    assert_eq!(
        doc.section_refs[0].target,
        Some("1-first-section".to_string())
    );
    assert!(doc.diagnostics.is_empty());
}

#[test]
fn test_stress_large_document() {
    use std::fmt::Write;
    let count = 5000;
    let mut md = String::with_capacity(count * 60);

    for i in 1..=count {
        let _ = writeln!(md, "This cites [R{i}] in paragraph {i}.\n");
    }

    let _ = writeln!(md, "# References\n");
    for i in 1..=count {
        let _ = writeln!(md, "[R{i}] Reference entry number {i} with details.\n");
    }

    let doc = parse(&Source::new(RelPath::new("large.md").unwrap(), md));

    assert_eq!(doc.reference_entries.len(), count);
    assert_eq!(doc.citations.len(), count);
    assert!(doc.diagnostics.is_empty());

    for (i, cit) in doc.citations.iter().enumerate() {
        let expected_label = format!("R{}", i + 1);
        let expected_target = format!("ref-r{}", i + 1);
        assert_eq!(cit.label, expected_label);
        assert_eq!(cit.target, Some(expected_target));
    }
}
