//! Generated documentation: projections of records that must not be edited
//! by hand. Each file starts with a header naming its sources and their
//! digest, so `cargo xtask docs --check` can report a stale projection.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde_json::Value;

use crate::error::{Context as _, Result};
use crate::evidence::TASKS_DIR;
use crate::lanes::relative;
use crate::tools::{self, BASELINE_PATH};
use crate::util::{sha256_file, sha256_hex};

/// Writes the generated docs, or with `check` reports stale ones (exit 1).
///
/// # Errors
/// Fails if a source cannot be read or a file cannot be written.
pub fn run(root: &Path, check: bool) -> Result<u8> {
    let generated = generate(root)?;
    if check {
        let stale: Vec<&str> = generated
            .iter()
            .filter(|(path, text)| {
                std::fs::read_to_string(root.join(path)).ok().as_deref() != Some(text)
            })
            .map(|(path, _)| path.as_str())
            .collect();
        if stale.is_empty() {
            println!("docs: {} generated files are current", generated.len());
            return Ok(0);
        }
        for path in stale {
            println!("stale: {path}");
        }
        println!("run `cargo xtask docs` and commit the result");
        return Ok(1);
    }
    for (path, text) in &generated {
        let full = root.join(path);
        if let Some(parent) = full.parent() {
            std::fs::create_dir_all(parent).context(|| format!("creating {}", parent.display()))?;
        }
        std::fs::write(&full, text).context(|| format!("writing {}", full.display()))?;
        println!("wrote {path}");
    }
    Ok(0)
}

/// Every generated file as (path relative to root, contents).
///
/// # Errors
/// Fails if a source cannot be read.
pub fn generate(root: &Path) -> Result<Vec<(String, String)>> {
    Ok(vec![
        ("docs/toolchain.md".to_owned(), toolchain(root)?),
        ("docs/evidence/index.md".to_owned(), evidence_index(root)?),
        ("docs/tasks/index.md".to_owned(), tasks_index(root)?),
    ])
}

fn header(sources: &str, inputs: &[(String, String)]) -> String {
    let mut listing = String::new();
    for (path, digest) in inputs {
        let _ = writeln!(listing, "{path}\t{digest}");
    }
    format!(
        "<!-- generated by cargo xtask docs from {sources} (sha256:{}); do not edit -->\n",
        sha256_hex(listing.as_bytes())
    )
}

fn cell(text: &str) -> String {
    text.replace('|', "\\|").replace('\n', " ")
}

fn toolchain(root: &Path) -> Result<String> {
    let baseline = tools::load(root)?;
    let digest = sha256_file(&root.join(BASELINE_PATH))?;
    let mut md = header(BASELINE_PATH, &[(BASELINE_PATH.to_owned(), digest)]);
    md.push_str(
        "\n# Toolchain and tools\n\n\
         `rha-baseline.json` owns the required version of every tool; the Rust toolchain is pinned in \
         `rust-toolchain.toml`. `cargo xtask ci` records a check as `not_run` when its tool is absent \
         (`tool_missing`) or at another version (`version_mismatch`).\n\n\
         | Tool | Status | Required | Used by | Install |\n| --- | --- | --- | --- | --- |\n",
    );
    for tool in &baseline.tools {
        let _ = writeln!(
            md,
            "| {} | {} | {} | {} | {} |",
            cell(&tool.name),
            cell(&tool.status),
            cell(tool.required.as_deref().unwrap_or("–")),
            cell(&if tool.used_by.is_empty() {
                "–".to_owned()
            } else {
                tool.used_by.join(", ")
            }),
            cell(&tool.install),
        );
    }
    Ok(md)
}

fn json_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(listing) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in listing.filter_map(std::result::Result::ok) {
        let path = entry.path();
        if path.is_dir() {
            json_files(&path, out);
        } else if path.extension().is_some_and(|x| x == "json") {
            out.push(path);
        }
    }
}

fn evidence_index(root: &Path) -> Result<String> {
    let mut files = Vec::new();
    json_files(&root.join("evidence"), &mut files);
    files.sort();
    let mut inputs = Vec::new();
    let mut rows = String::new();
    for path in &files {
        let rel = relative(root, path);
        inputs.push((rel.clone(), sha256_file(path)?));
        let text =
            std::fs::read_to_string(path).context(|| format!("reading {}", path.display()))?;
        let Ok(record) = serde_json::from_str::<Value>(&text) else {
            let _ = writeln!(rows, "| `{rel}` | unparsable | | | | | | |");
            continue;
        };
        let s = |p: &str| {
            record
                .pointer(p)
                .and_then(Value::as_str)
                .unwrap_or("?")
                .to_owned()
        };
        let revision = s("/artifact_identity/revision");
        let dirty = record
            .pointer("/artifact_identity/dirty")
            .and_then(Value::as_bool)
            .map_or("?", |d| if d { "yes" } else { "no" });
        let mut counts: Vec<(String, u32)> = Vec::new();
        for check in record
            .pointer("/observed_checks")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
        {
            let outcome = check
                .get("outcome")
                .and_then(Value::as_str)
                .unwrap_or("?")
                .to_owned();
            match counts.iter_mut().find(|(o, _)| *o == outcome) {
                Some((_, n)) => *n += 1,
                None => counts.push((outcome, 1)),
            }
        }
        let outcomes = counts
            .iter()
            .map(|(o, n)| format!("{n} {o}"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            rows,
            "| [{}](../../{rel}) | {} | {} | {} | `{}` | {dirty} | {} | {} |",
            cell(rel.trim_start_matches("evidence/")),
            cell(&s("/lane")),
            cell(&s("/evidence_class")),
            cell(&s("/change_claim/task")),
            revision.get(..12).unwrap_or(&revision),
            cell(&outcomes),
            cell(&s("/disposition/eligibility")),
        );
    }
    let mut md = header("evidence/**/*.json", &inputs);
    md.push_str(
        "\n# Evidence records\n\n\
         Every record is advisory: class `local` or `ci`, produced by candidate code and not \
         authenticated (see [the threat model](../threat-model.md)). Eligibility `blocked` lists its \
         reasons per acceptance predicate inside the record.\n\n\
         | Record | Lane | Class | Task | Revision | Dirty | Outcomes | Eligibility |\n\
         | --- | --- | --- | --- | --- | --- | --- | --- |\n",
    );
    md.push_str(&rows);
    if files.is_empty() {
        md.push_str("\nNo records yet.\n");
    }
    Ok(md)
}

fn tasks_index(root: &Path) -> Result<String> {
    let mut files: Vec<PathBuf> = std::fs::read_dir(root.join(TASKS_DIR))
        .map(|l| {
            l.filter_map(std::result::Result::ok)
                .map(|e| e.path())
                .filter(|p| p.extension().is_some_and(|x| x == "toml"))
                .collect()
        })
        .unwrap_or_default();
    files.sort();
    let mut inputs = Vec::new();
    let mut rows = String::new();
    for path in &files {
        let rel = relative(root, path);
        inputs.push((rel.clone(), sha256_file(path)?));
        let text =
            std::fs::read_to_string(path).context(|| format!("reading {}", path.display()))?;
        let table: toml::Table =
            toml::from_str(&text).context(|| format!("parsing {}", path.display()))?;
        let s = |key: &str| {
            table
                .get(key)
                .and_then(toml::Value::as_str)
                .unwrap_or("?")
                .to_owned()
        };
        let executors = table
            .get("roles")
            .and_then(|r| r.get("executor"))
            .and_then(toml::Value::as_array)
            .map_or_else(
                || "?".to_owned(),
                |a| {
                    a.iter()
                        .filter_map(toml::Value::as_str)
                        .collect::<Vec<_>>()
                        .join(", ")
                },
            );
        let _ = writeln!(
            rows,
            "| [{}](../../{rel}) | {} | {} | {} | {} | {} |",
            cell(&s("id")),
            cell(&s("title")),
            cell(&s("mode")),
            cell(&executors),
            cell(&s("authority_profile")),
            cell(&s("status")),
        );
    }
    let mut md = header(".rha/tasks/*.toml", &inputs);
    md.push_str(
        "\n# Tasks\n\n\
         One task record per change (spec §11.7.11, stored as TOML). A task's status is the \
         Executor's proposal; acceptance is recorded separately in `.rha/acceptances/`.\n\n\
         | Task | Title | Mode | Executors | Authority | Status |\n| --- | --- | --- | --- | --- | --- |\n",
    );
    md.push_str(&rows);
    Ok(md)
}
